require:
  - rubocop-rails

AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.3.0
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/**/*
    - vendor/**/*

Rails:
  Enabled: true

Style/GuardClause:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 180

Metrics/BlockLength:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Style/ClassAndModuleChildren:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ParameterLists:
  Max: 8

Style/SafeNavigation:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/DeprecatedActiveModelErrorsMethods:
  Enabled: false